on: [pull_request]
# pull_request:
#   types:
#     - closed

jobs:
  # alert-not-merged:
  #   name: Alert No Merge
  #   runs-on: ubuntu-latest
  #   if: github.event.pull_request.merged != true
  #   steps:
  #     - run: echo "PR closed but not merged, do nothing."

  call-import-webhook:
    name: Call Webhook
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: wget and wait for response
        env:
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
        run: |
          echo "${{ secrets.WEBHOOK_TOKEN }}"
          echo "$WEBHOOK_TOKEN"
          wget -S https://io.adafruit.com/wipper_releases?token=${{ secrets.WEBHOOK_TOKEN }} 2>&1 | awk '/^  HTTP/{print $2}'
          wget -S https://io.adafruit.com/wipper_releases?token=$WEBHOOK_TOKEN 2>&1 | awk '/^  HTTP/{print $2}'

          if [ $? = 200 ]; then
            echo "Something went wrong"
            exit 1
          else
            echo "All good"
          fi
