name: Validate JSON and Filenames

on: [pull_request]

jobs:
  validate-board-definition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Validate Board JSON
      #   uses: nhalstead/validate-json-action@0.1.3
      #   with:
      #     # Schema Docs: https://ajv.js.org/json-schema.html#json-data-type
      #     schema: /boards/schema.json
      #     jsons: boards/*/definition.json

      - name: List Changed Board Files
        id: changed-files
        uses: tj-actions/changed-files@v21
        with:
          files: boards/**/*

      # - name: Validate Only Expected Filenames
      #   env:
      #     FILES: ${{ steps.changed-files.outputs.renamed_files }} ${{ steps.changed-files.outputs.added_files }}
      #   run: |
      #     exit_value=0
      #     board_definition_regex="^boards\/.*\/(definition\.json|((image|images\/(boot-(drive|loader)|drag-drop|reset|usb))\.(png|jpe?g|gif)))$"
      #
      #     for file in $FILES; do
      #       if [[ $file =~ $board_definition_regex ]]; then
      #         echo "✅ $file"
      #       else
      #         echo "❌ $file"
      #         exit_value=1
      #       fi
      #     done
      #
      #     exit $exit_value
      #
      # - name: Validate Image File Extension<->Mimetype Agreement
      #   env:
      #     FILES: ${{ steps.changed-files.outputs.renamed_files }} ${{ steps.changed-files.outputs.added_files }}
      #   run: |
      #     exit_value=0
      #
      #     for file in $FILES; do
      #       # check each file's mimetype matches its extension
      #       MIME=`file -b --mime-type $file`
      #       EXT="${file##*.}"
      #
      #       if [[ "image/$EXT" == $MIME || ($EXT == "jpg" && $MIME == "image/jpeg") ]]; then
      #         echo "✅ $file"
      #
      #       else
      #         # Doesn't match? Report it helpfully
      #         # split the mimetype on '/'
      #         IFS='/'
      #         read -a SPLIT_MIME <<< "$MIME"
      #         IFS=' '
      #         MIME_EXT=${SPLIT_MIME[-1]} # last item
      #         NEW_FILE="${file%.$EXT}.$MIME_EXT"
      #         echo "❌ $file: rename to $NEW_FILE"
      #
      #         exit_value=1
      #       fi
      #     done
      #
      #     exit $exit_value


      - uses: mfinelli/setup-imagemagick@v1

      - name: Validate Image Dimensions
        env:
          FILES: ${{ steps.changed-files.outputs.renamed_files }} ${{ steps.changed-files.outputs.added_files }}
        run: |
          exit_value=0

          for file in $FILES; do
            # use imagemagick for the width
            WIDTH=`identify -ping -format "%w" $file`
            BAD_WIDTH=false
            if [[ WIDTH > 800 ]]; then
              exit_value = 1
              BAD_WIDTH=true
            fi

            # use imagemagick for the width
            HEIGHT=`identify -ping -format "%h" $file`
            BAD_HEIGHT=false
            if [[ HEIGHT > 2000 ]]; then
              exit_value = 1
              BAD_HEIGHT=true
            fi

            if [[ BAD_WIDTH || BAD_HEIGHT ]]; then
              echo "❌ $file:"
              if [[ BAD_WIDTH ]]; then
                echo "↔️ width > 800 pixels"
              fi

              if [[ BAD_HEIGHT ]]; then
                echo "↕️ height > 2000 pixels"
              fi

            else
              echo "✅ $file $WIDTH x $HEIGHT"
            fi
          done

          exit $exit_value

      - name: Optimize All Image Files
        run: echo "TODO"

      - name: Validate Image File Sizes
        run: echo "TODO"

      - name: Add & Commit (maybe branch and PR?)
        run: echo "TODO"

      - name: Leave Helpful Comment
        run: echo "TODO"
